export type PostexPackageKind = 'box' | 'envelope' | 'oversize';

export type PostexPackageDefinition = {
  boxTypeId: number;
  code: string;
  title: string;
  kind: PostexPackageKind;
  lengthCm: number;
  widthCm: number;
  heightCm: number;
  enabled: boolean;
  allowFragile: boolean;
  allowLiquid: boolean;
};

export const POSTEX_PACKAGES: PostexPackageDefinition[] = [
  {
    boxTypeId: 1,
    code: 'BOX_1',
    title: 'جعبه سایز ۱',
    kind: 'box',
    lengthCm: 15,
    widthCm: 10,
    heightCm: 10,
    enabled: true,
    allowFragile: true,
    allowLiquid: true,
  },
  {
    boxTypeId: 2,
    code: 'BOX_2',
    title: 'جعبه سایز ۲',
    kind: 'box',
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10,
    enabled: true,
    allowFragile: true,
    allowLiquid: true,
  },
  {
    boxTypeId: 3,
    code: 'BOX_3',
    title: 'جعبه سایز ۳',
    kind: 'box',
    lengthCm: 20,
    widthCm: 20,
    heightCm: 15,
    enabled: true,
    allowFragile: true,
    allowLiquid: true,
  },
  {
    boxTypeId: 4,
    code: 'BOX_4',
    title: 'جعبه سایز ۴',
    kind: 'box',
    lengthCm: 30,
    widthCm: 20,
    heightCm: 20,
    enabled: true,
    allowFragile: true,
    allowLiquid: true,
  },
  {
    boxTypeId: 5,
    code: 'BOX_5',
    title: 'جعبه سایز ۵',
    kind: 'box',
    lengthCm: 35,
    widthCm: 25,
    heightCm: 20,
    enabled: true,
    allowFragile: true,
    allowLiquid: true,
  },
  {
    boxTypeId: 6,
    code: 'BOX_6',
    title: 'جعبه سایز ۶',
    kind: 'box',
    lengthCm: 45,
    widthCm: 25,
    heightCm: 20,
    enabled: true,
    allowFragile: true,
    allowLiquid: true,
  },
  {
    boxTypeId: 7,
    code: 'BOX_7',
    title: 'جعبه سایز ۷',
    kind: 'box',
    lengthCm: 40,
    widthCm: 30,
    heightCm: 25,
    enabled: true,
    allowFragile: true,
    allowLiquid: true,
  },
  {
    boxTypeId: 8,
    code: 'BOX_8',
    title: 'جعبه سایز ۸',
    kind: 'box',
    lengthCm: 45,
    widthCm: 40,
    heightCm: 30,
    enabled: true,
    allowFragile: true,
    allowLiquid: true,
  },
  {
    boxTypeId: 9,
    code: 'BOX_9',
    title: 'جعبه سایز ۹',
    kind: 'box',
    lengthCm: 55,
    widthCm: 45,
    heightCm: 35,
    enabled: true,
    allowFragile: true,
    allowLiquid: true,
  },
  {
    boxTypeId: 10,
    code: 'BOX_LARGER_THAN_9',
    title: 'جعبه بزرگتر از سایز ۹',
    kind: 'oversize',
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    enabled: true,
    allowFragile: true,
    allowLiquid: true,
  },
  {
    boxTypeId: 11,
    code: 'ENVELOPE_A5',
    title: 'پاکت نامه A5',
    kind: 'envelope',
    lengthCm: 22,
    widthCm: 11,
    heightCm: 1,
    enabled: true,
    allowFragile: false,
    allowLiquid: false,
  },
  {
    boxTypeId: 12,
    code: 'ENVELOPE_A4',
    title: 'پاکت نامه A4',
    kind: 'envelope',
    lengthCm: 31,
    widthCm: 22,
    heightCm: 1,
    enabled: true,
    allowFragile: false,
    allowLiquid: false,
  },
  {
    boxTypeId: 13,
    code: 'ENVELOPE_A3',
    title: 'پاکت نامه A3',
    kind: 'envelope',
    lengthCm: 45,
    widthCm: 30,
    heightCm: 1,
    enabled: true,
    allowFragile: false,
    allowLiquid: false,
  },
];